// `krimto --help` — surface every subcommand so a user who didn't read the README can still
// discover them. v0.2.32 rewrite: previous version listed 14 of 28 dispatched commands. The
// missing 14 (status, editors, search, service, reset, stop, start, restart, edit, mv,
// supersede, tag, notes, join, team, delete, set identity, plus the deprecated aliases) were
// stranded in the source — users had no way to find them. Now everything is grouped by what
// the user wants to accomplish, not by which internal subsystem owns the implementation.

/** Build the help text printed by `krimto --help` / `krimto -h` / `krimto help`. */
export function formatHelp(version: string): string {
  return [
    "",
    `✅ krimto — team memory for AI coding agents (v${version})`,
    "",
    "━━ Two ways to use Krimto ━━",
    "",
    "  DEFAULT MODE  Your agent uses Krimto only when you say \"use krimto to ...\".",
    "                Setup: `connect` (paste config into your editor).",
    "",
    "  AUTO MODE     Your agent uses Krimto automatically (no prefix needed).",
    "                Setup: `init` walks the whole flow in one command.",
    "",
    "━━ Usage ━━",
    "",
    "  $ npx @krimto-labs/krimto [command]",
    "",
    "━━ Get connected ━━",
    "",
    "  init [--yes]            Set up Krimto (interactive wizard, or all defaults with --yes)",
    "  init --minimal          Skip the wizard; write the rule for detected editors only",
    "  init --all              Write the rule to all 4 supported editor files",
    "  connect                 Print MCP config snippets for Claude Code & Cursor",
    "  uninit                  Switch this project back to DEFAULT MODE (rule only)",
    "",
    "━━ Look at your notes ━━",
    "",
    "  notes [query]           List or search notes (terminal)",
    "  ui                      Open the browser dashboard (http://localhost:8080/ui)",
    "  open                    Reveal the notes folder in your OS file manager",
    "  edit <id>               Open the fact's .md in $EDITOR, reindex on save",
    "  mv <id> <scope>         Move a fact to a different scope (id preserved)",
    "  supersede <id>          Replace a fact with a new version (old kept in git)",
    "  tag <id> +new -old      Add / remove tags",
    "  rm <id>                 Delete a fact (file + index + git commit)",
    "",
    "━━ Stop & reset ━━",
    "",
    "  stop                    Stop the running krimto (service or ad-hoc)",
    "  start                   Start krimto (if a service was installed)",
    "  restart                 stop + start",
    "  uninit                  Project-only undo (rule files only)",
    "  reset [--yes]           Disconnect every editor + service (notes preserved)",
    "  reset --wipe-notes      Also delete the data dir (asks twice)",
    "",
    "━━ Is it working? ━━",
    "",
    "  status                  One screen — running? where? recent activity?",
    "  whoami                  Which identity am I writing as? (and where it's set)",
    "  verify-connection       → status",
    "  where  / storage / usage  → status (kept for back-compat)",
    "",
    "━━ Configure (after first run) ━━",
    "",
    "  editors                 Add / remove editor MCP connections",
    "  service [--as-needed | --always | --manual]  Switch run mode (or use `stop` / `start`)",
    "  search                  Switch search provider (Keyword / OpenAI)",
    "  remote                  Show / set / remove the git remote",
    "  folder --to <path>      Move the notes folder to a new location",
    "  set identity <email>    Change KRIMTO_IDENTITY everywhere",
    "",
    "━━ Team ━━",
    "",
    "  team init               Set up team mode (admin + members + git remote)",
    "  team disband            Step back to solo mode (notes preserved)",
    "  join --server <url> --key <key>   Join an existing team",
    "",
    "━━ Advanced / scripting ━━",
    "",
    "  serve                   Start the HTTP server in the foreground (port 8080)",
    "  reindex                 Rebuild index.db from markdown",
    "  setup-remote <url>      One-shot git remote setup (also under `remote`)",
    "  setup-embeddings        Verify KRIMTO_EMBED_* with one test request",
    "  delete <id>             Alias for `rm`",
    "  (no args)               Start the stdio MCP server (for MCP clients to launch)",
    "  --help, -h              Show this help",
    "",
    "━━ Environment variables ━━",
    "",
    "  KRIMTO_DATA              Override the data directory (default: ~/.krimto)",
    "  KRIMTO_IDENTITY          Identity used for writes (default: user@localhost)",
    "  KRIMTO_HTTP_PORT         Serve MCP over HTTP on this port instead of stdio",
    "  KRIMTO_BOOTSTRAP_ADMIN   First-admin email — turns on team mode + key auth",
    "",
    "Learn more: https://krimto.com · https://github.com/krimto-labs/krimto",
    "",
  ].join("\n");
}
