// `krimto --help` — list every subcommand a user could otherwise only discover by reading the README.
// Single source of truth so bin/krimto.mjs and any future surface can't drift.

/** Build the help text printed by `krimto --help` / `krimto -h` / `krimto help`. */
export function formatHelp(version: string): string {
  return [
    "",
    `✅ krimto — team memory for AI coding agents (v${version})`,
    "",
    "━━ Two ways to use Krimto ━━",
    "",
    "  DEFAULT MODE  Your agent uses Krimto only when you say \"use krimto to ...\".",
    "                Setup: `connect` (paste config into your editor).",
    "",
    "  AUTO MODE     Your agent uses Krimto automatically (no prefix needed).",
    "                Setup: `connect`, then `init` once per project.",
    "                Switch back: `uninit`.",
    "",
    "━━ Usage ━━",
    "",
    "  $ npx @krimto-labs/krimto [command]",
    "",
    "━━ Commands ━━",
    "",
    "  Get connected:",
    "    serve              Start the HTTP server (port 8080) + browser /ui dashboard",
    "    connect            Print copy-paste config for Claude Code & Cursor",
    "    init [--minimal]   Switch project to AUTO MODE — write the rule (default: all 4 files)",
    "    uninit             Switch back to DEFAULT MODE",
    "",
    "  Learn:",
    "    usage              Show the 5 krimto_* tools with chat examples",
    "    storage            Explain where Krimto keeps your data",
    "    where              Print the Krimto data directory",
    "",
    "  Manage facts:",
    "    rm <id>            Delete a fact (file + index + git deletion commit)",
    "    reindex            Rebuild index.db from markdown (fixes manual-delete orphans)",
    "",
    "  Identity:",
    "    whoami             Show which email Krimto is using (and where it's set)",
    "    set identity <e>   Change the identity used for new fact writes",
    "",
    "  Diagnose:",
    "    verify-connection  Is my agent actually calling Krimto? (live status + last 5 calls)",
    "    setup-remote <url> Wire data dir to a git remote, verify the push works",
    "    setup-embeddings   Verify KRIMTO_EMBED_* config with a real test request",
    "",
    "  Other:",
    "    (no args)          Start the stdio MCP server (for MCP clients to launch)",
    "    --help, -h         Show this help",
    "",
    "━━ Environment variables ━━",
    "",
    "  KRIMTO_DATA              Override the data directory (default: ~/.krimto)",
    "  KRIMTO_IDENTITY          Identity used for writes (default: user@localhost)",
    "  KRIMTO_HTTP_PORT         Serve MCP over HTTP on this port instead of stdio",
    "  KRIMTO_BOOTSTRAP_ADMIN   First-admin email — turns on team mode + key auth",
    "",
    "Learn more: https://krimto.com · https://github.com/krimto-labs/krimto",
    "",
  ].join("\n");
}
