// `krimto --help` — list every subcommand a user could otherwise only discover by reading the README.
// Single source of truth so bin/krimto.mjs and any future surface can't drift.

/** Build the help text printed by `krimto --help` / `krimto -h` / `krimto help`. */
export function formatHelp(version: string): string {
  return [
    `krimto — open-source team memory layer for AI coding agents (v${version})`,
    "",
    "TWO WAYS TO USE KRIMTO",
    "  DEFAULT MODE — your agent uses Krimto only when you explicitly ask",
    '    ("use krimto to remember X" / "use krimto to recall what we know").',
    "    Setup: paste the `connect` snippet into your editor's MCP config.",
    "    Want the browser dashboard too? Run `serve` (no Docker / no clone needed).",
    "",
    "  AUTO MODE — your agent uses Krimto automatically: recall before tasks,",
    '    save what it learns when you say "remember".',
    "    Setup: `connect` (as above), THEN run `init` once in your project.",
    "    Switch back to DEFAULT MODE at any time with `uninit`.",
    "",
    "Usage:",
    "  npx @krimto-labs/krimto [command]",
    "",
    "Commands:",
    "  (no args)    Start the stdio MCP server (default; for MCP clients to launch)",
    "  serve        Start the HTTP server (port 8080) — gives you /ui dashboard",
    "               → use this if you want the browser UI without Docker / pnpm",
    "  connect      Print copy-paste config snippets for Claude Code & Cursor",
    "               → use this once per editor / per machine",
    "  init [--all] Switch this project to AUTO MODE — write the always-use rule",
    "               → use this once per project (auto-detects your editor; --all = every file)",
    "  uninit       Switch this project back to DEFAULT MODE — remove the rule",
    "               → cleanly reverses `init` (deletes files it created)",
    "  usage        Show the five krimto_* tools and chat examples for both modes",
    "               → read this AFTER `connect` to learn how to actually use Krimto",
    "  storage      Explain where Krimto keeps your data (markdown / git / index)",
    "               → run this to see what's on your disk and what you can edit",
    "  setup-remote Wire the data dir to a git remote and verify the push works",
    "               → one-time setup for cross-machine / teammate sync",
    "  setup-embeddings",
    "               Verify a KRIMTO_EMBED_* config by sending a real test embedding",
    "               → one-time check before turning on semantic / vector search",
    "  verify-connection",
    "               Diagnose if your agent is actually calling Krimto (live status + last 5 calls)",
    "               → run this when 'I asked the agent but recall returned nothing'",
    "  where        Print the Krimto data directory",
    "  --help, -h   Show this help",
    "",
    "Environment:",
    "  KRIMTO_DATA              Override the data directory (default: ~/.krimto)",
    "  KRIMTO_IDENTITY          Identity used for writes (default: user@localhost)",
    "  KRIMTO_HTTP_PORT         Serve MCP over HTTP on this port instead of stdio",
    "  KRIMTO_BOOTSTRAP_ADMIN   First-admin email — turns on team mode + key auth",
    "",
    "Learn more: https://krimto.com · https://github.com/krimto-labs/krimto",
    "",
  ].join("\n");
}
