// `krimto storage` — explain where Krimto keeps things on disk, in plain English. The "you own
// your data" half of Krimto's pitch is invisible to a first-time user unless we teach it. This
// command is that lesson, on demand, with no docs to chase.

/** Build the storage explainer printed by `krimto storage`. */
export function formatStorage(dataDir: string): string {
  return [
    "krimto — where your data actually lives",
    "",
    `Your Krimto folder is here:`,
    `  ${dataDir}`,
    "",
    "✅ ALREADY SET UP — YOU DON'T HAVE TO DO ANYTHING",
    "  Both the git repo and the search index were created automatically the",
    "  first time you ran Krimto. There is no setup step. Every save commits to",
    "  git on its own (batched every 30s or every 10 writes). The index keeps",
    "  itself in sync with the markdown.",
    "",
    "Inside the folder, three things do three jobs:",
    "",
    "1. MARKDOWN FILES — the real brain (the source of truth)",
    "   One fact = one .md file. Plain text. Open any of them in any editor.",
    "   Layout:",
    "     <data>/user/<email>/<slug>.md     ← your personal notes",
    "     <data>/team/<slug>/<slug>.md      ← team-shared notes",
    "     <data>/org/<slug>/<slug>.md       ← org-wide notes",
    "   Top of each file: YAML metadata (id, scope, author, timestamps).",
    "   Bottom: the markdown body. That's it. No proprietary format.",
    "",
    "2. GIT REPO — the audit log (auto-initialized on first boot)",
    "   The .git/ folder inside is a real git repository, created for you. Krimto",
    "   commits every change it makes (batched every 30s or every 10 writes).",
    "   Useful commands you can run from inside the folder:",
    "     git log         — see who wrote what, when",
    "     git blame <file>— who last touched this line",
    "     git revert <sha>— roll back a bad fact",
    "",
    "3. INDEX.DB — the fast librarian (a cache, not the source of truth)",
    "   SQLite full-text + vector index over your markdown, built for you. Lets",
    "   recall return in milliseconds instead of grepping every file. You can",
    "   delete it any time — Krimto rebuilds it from the markdown on next boot.",
    "   It's gitignored.",
    "",
    "HOW TO CHECK IT'S WORKING",
    `  cd ${dataDir}`,
    "  git log --oneline       — should show 'krimto: write batch — N facts'",
    "  ls index.db             — should exist (created on first boot)",
    "  ls user/ team/ org/     — your scopes (only the ones you've used)",
    "",
    "  Note: commits are BATCHED every 30 seconds (or every 10 writes), so a fact",
    "  you saved just now may not appear in `git log` for up to ~30s. The .md file",
    "  itself is written immediately — `ls` it in the scope folder to confirm.",
    "",
    "OPTIONAL: SHARE & UPGRADE",
    "  These are the only two things you might want to set up — both optional.",
    "  Krimto works fully without them.",
    "",
    "  → Share the notebook across machines / teammates (git remote):",
    "      KRIMTO_GIT_REMOTE=git@github.com:acme/krimto-data.git",
    "    Set this env var before starting Krimto. Every batch commit is pushed",
    "    to that remote; Krimto also pulls every 60s for teammates' edits.",
    "",
    "  → Smarter recall — semantic / vector search (embedding provider):",
    "      KRIMTO_EMBED_PROVIDER=openai",
    "      KRIMTO_EMBED_API_KEY=sk-...",
    "    Without this, recall uses keyword search (BM25) only. With it, recall",
    "    also matches paraphrases. Other providers: voyage, openai-compatible.",
    "",
    "WHAT YOU CAN DO BY HAND",
    "  • Open any .md in your editor and read it as plain text.",
    "  • Edit a fact by hand — Krimto picks up your change on the next sync (60s).",
    `  • Move the whole folder to another laptop, set KRIMTO_DATA=<new path>, done.`,
    "  • Back it up with cp, or push to a private GitHub repo.",
    "  • If Krimto vanished tomorrow, you'd still have every fact (it's just files).",
    "",
    "WHAT YOU SHOULDN'T DO",
    "  • Don't edit index.db. It gets rebuilt from markdown — your edits are lost.",
    "  • Don't edit the frontmatter `id`, `created`, or `updated` fields.",
    "    Those are server-controlled.",
    "  • Don't store secrets in facts. They're in git history forever.",
    "",
    "WHY THIS DESIGN",
    "  Other memory tools lock your notes in a database you can't open. Krimto",
    "  stores them as files you can read with your eyes, in a folder you own,",
    "  tracked by the same tool engineers already trust for code. The fast index",
    "  on top is there so the agent doesn't pay for the readability.",
    "",
    "RELATED COMMANDS",
    "  krimto where    Print just the data directory (no explanation)",
    "  krimto usage    Learn how to use the five krimto_* tools",
    "  krimto --help   List every CLI command",
    "",
  ].join("\n");
}
