// `krimto storage` — explain where Krimto keeps things on disk, in plain English. The "you own
// your data" half of Krimto's pitch is invisible to a first-time user unless we teach it. This
// command is that lesson, on demand, with no docs to chase.

/** Build the storage explainer printed by `krimto storage`. */
export function formatStorage(dataDir: string): string {
  return [
    "",
    "✅ Krimto storage — already set up, no action needed",
    "",
    `   Data folder: ${dataDir}`,
    "",
    "━━ Three things inside ━━",
    "",
    "  📝 Markdown files   ← the real data",
    "     One .md per fact. Plain text. Open in any editor.",
    "     Layout: <data>/{user,team,org}/<id>/<slug>.md",
    "",
    "  📚 Git repo (.git/)  ← the audit log (auto-commits every 30s)",
    "     `git log`, `git blame`, `git revert` all work as normal.",
    "",
    "  ⚡ index.db          ← just a cache (gitignored)",
    "     Rebuilt from the markdown on next boot. You can ignore it.",
    "",
    "━━ Verify it's working ━━",
    "",
    `  $ cd ${dataDir}`,
    "  $ git log --oneline       # commits batched ~30s after each fact",
    "  $ ls index.db             # exists since first boot",
    "  $ ls user/ team/ org/     # your scopes",
    "",
    "  Note: a fact saved right now may not appear in `git log` for up to ~30s",
    "  (commits are batched). The .md file is written immediately.",
    "",
    "━━ Optional: share / smarter recall ━━",
    "",
    "  Cross-machine / teammate sync:",
    "    KRIMTO_GIT_REMOTE=git@github.com:acme/krimto-data.git",
    "    → safely: $ npx krimto setup-remote <url>",
    "",
    "  Semantic recall (matches paraphrases):",
    "    KRIMTO_EMBED_PROVIDER=openai",
    "    KRIMTO_EMBED_API_KEY=sk-...",
    "    → verify first: $ npx krimto setup-embeddings",
    "",
    "━━ Things you CAN do by hand ━━",
    "",
    "  • Open any .md and read/edit it (Krimto re-indexes on next sync)",
    "  • Move the folder to another laptop (set KRIMTO_DATA=<new path>)",
    "  • Back up with `cp`, or push to a private GitHub repo",
    "  • If Krimto vanished, you'd still have every fact (it's just files)",
    "",
    "━━ Don't touch ━━",
    "",
    "  ✗ index.db (rebuilt — your edits are lost)",
    "  ✗ Frontmatter id / created / updated (server-controlled)",
    "  ✗ Don't store secrets — git history is forever",
    "",
    "Related: $ krimto where · $ krimto usage · $ krimto --help",
    "",
  ].join("\n");
}
